apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: cbci-ops-secret-provider
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/core-workshop/secrets/cbci-casc-gitops-github-app-pem/versions/latest"
        fileName: "cbciCascGitOpsGitHubAppPem"
      - resourceName: "projects/core-workshop/secrets/beedemo-dev-github-pat/versions/latest"
        fileName: "beedemoDevGithubPat"
      - resourceName: "projects/core-workshop/secrets/cbci-workshop-github-app-webhook-secret/versions/latest"
        fileName: "gitHubWebhookSecret"
      - resourceName: "projects/core-workshop/secrets/cbci-workshop-oc-admin-api-token/versions/latest"
        fileName: "cbciWorkshopCjocAdminToken"
      - resourceName: "projects/core-workshop/secrets/cbci-workshop-attendee-password/versions/latest"
        fileName: "cbciWorkshopAttendeePassword"
      - resourceName: "projects/core-workshop/secrets/cbci-workshop-slack-token/versions/latest"
        fileName: "workshopSlackToken"
      - resourceName: "projects/core-workshop/secrets/cbci-workshop-oc-admin-api-token/versions/latest"
        fileName: "apiToken"
                