apiVersion: v1
kind: PersistentVolume
metadata:
  name: jcasc-bundles-store
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: topology.gke.io/zone
          operator: In
          values:
          - us-east1-c
      - matchExpressions:
        - key: topology.gke.io/zone
          operator: In
          values:
          - us-east1-b
  persistentVolumeReclaimPolicy: Delete
  storageClassName: regional-pd-ssd-csi-storageclass
  volumeMode: Filesystem