apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: cbci-mc-secret-provider
spec:
  provider: gcp
  secretObjects:
  - secretName: cbci-mc-secret
    type: Opaque
    data: 
    - objectName: gitHubAppPrivateKey
      key: gitHubAppPrivateKey
    - objectName: gitHubAppId
      key: gitHubAppId
    - objectName: staging-gitHubAppPrivateKey
      key: staging-gitHubAppPrivateKey
    - objectName: staging-gitHubAppId
      key: staging-gitHubAppId
    - objectName: slackToken
      key: slackToken
    - objectName: gitHubWebhookSecret
      key: gitHubWebhookSecret
    - objectName: featureFlagWorkshopGitHubAppPrivateKey
      key: featureFlagWorkshopGitHubAppPrivateKey
    - objectName: cbciPipelineWorkshopGitHubAppPrivateKey
      key: cbciPipelineWorkshopGitHubAppPrivateKey
    - objectName: cbciPipelineWorkshopFmKey
      key: cbciPipelineWorkshopFmKey
    - objectName: cbciWorkshopExampleCredentialServicePassword
      key: cbciWorkshopExampleCredentialServicePassword
    - objectName: cbciCascWorkshopGitHubAppPrivateKey
      key: cbciCascWorkshopGitHubAppPrivateKey
    - objectName: cbciCascWorkshopGitHubAppId
      key: cbciCascWorkshopGitHubAppId
    - objectName: cbciCascWorkshopControllerProvisionSecret
      key: cbciCascWorkshopControllerProvisionSecret
    - objectName: cascUpdateSecret
      key: cascUpdateSecret
    - objectName: staging-cbciCascWorkshopGitHubAppPrivateKey
      key: staging-cbciCascWorkshopGitHubAppPrivateKey
    - objectName: staging-cbciCascWorkshopGitHubAppId
      key: staging-cbciCascWorkshopGitHubAppId
    - objectName: userApiToken
      key: userApiToken
    - objectName: cbciPreviewsDemoGitHubAppPrivateKey
      key: cbciPreviewsDemoGitHubAppPrivateKey
  parameters:
    secrets: | 
      - resourceName: "projects/core-workshop/secrets/cbci-workshop-github-app-pem/versions/latest"
        fileName: "gitHubAppPrivateKey"
      - resourceName: "projects/core-workshop/secrets/cbci-workshop-github-app-id/versions/latest"
        fileName: "gitHubAppId"
      - resourceName: "projects/core-workshop/secrets/cbci-workshop-slack-token/versions/latest"
        fileName: "slackToken"
      - resourceName: "projects/core-workshop/secrets/cbci-workshop-github-app-webhook-secret/versions/latest"
        fileName: "gitHubWebhookSecret"
      - resourceName: "projects/core-workshop/secrets/cbff-workshop-github-app-pem/versions/latest"
        fileName: "featureFlagWorkshopGitHubAppPrivateKey"
      - resourceName: "projects/core-workshop/secrets/cbci-pipeline-workshop-github-app-pem/versions/latest"
        fileName: "cbciPipelineWorkshopGitHubAppPrivateKey"
      - resourceName: "projects/core-workshop/secrets/cbci-pipeline-workshop-fm-key/versions/latest"
        fileName: "cbciPipelineWorkshopFmKey"
      - resourceName: "projects/core-workshop/secrets/cbci-workshop-example-credential-password/versions/latest"
        fileName: "cbciWorkshopExampleCredentialServicePassword"
      - resourceName: "projects/core-workshop/secrets/cbci-casc-workshop-github-app-pem/versions/latest"
        fileName: "cbciCascWorkshopGitHubAppPrivateKey"
      - resourceName: "projects/core-workshop/secrets/cbci-casc-workshop-github-app-id/versions/latest"
        fileName: "cbciCascWorkshopGitHubAppId"
      - resourceName: "projects/core-workshop/secrets/cbci-casc-workshop-controller-provision-secret/versions/latest"
        fileName: "cbciCascWorkshopControllerProvisionSecret"
      - resourceName: "projects/core-workshop/secrets/cbci-casc-workshop-controller-provision-secret/versions/latest"
        fileName: "cascUpdateSecret"
      - resourceName: "projects/624756700378/secrets/staging-cbci-workshop-github-app-pem/versions/latest"
        fileName: "staging-gitHubAppPrivateKey"
      - resourceName: "projects/624756700378/secrets/staging-cbci-workshop-github-app-id/versions/latest"
        fileName: "staging-gitHubAppId"
      - resourceName: "projects/core-workshop/secrets/staging-cbci-casc-workshop-github-app-pem/versions/latest"
        fileName: "staging-cbciCascWorkshopGitHubAppPrivateKey"
      - resourceName: "projects/core-workshop/secrets/staging-cbci-casc-workshop-github-app-id/versions/latest"
        fileName: "staging-cbciCascWorkshopGitHubAppId"
      - resourceName: "projects/core-workshop/secrets/cbci-casc-workshop-user-api-token/versions/latest"
        fileName: "userApiToken" 
      - resourceName: "projects/core-workshop/secrets/cbci-previews-demo-github-app-pem/versions/latest"
        fileName: "cbciPreviewsDemoGitHubAppPrivateKey"
