apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cbci-ops-controllers-agents
  namespace: controllers
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cjoc-agents
subjects:
- kind: ServiceAccount
  name: jenkins
  namespace: cbci

