apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: cbci-mc-secret-provider
spec:
  provider: gcp
  secretObjects:
  parameters:
    secrets: | 
      - resourceName: "projects/core-workshop/secrets/cbci-casc-gitops-github-app-pem/versions/latest"
        fileName: "cbciCascGitOpsGitHubAppPem"
      - resourceName: "projects/core-workshop/secrets/cbci-workshop-github-app-webhook-secret/versions/latest"
        fileName: "gitHubWebhookSecret"
      - resourceName: "projects/core-workshop/secrets/cbci-workshop-slack-token/versions/latest"
        fileName: "workshopSlackToken"
      - resourceName: "projects/core-workshop/secrets/cbci-casc-workshop-controller-provision-secret/versions/latest"
        fileName: "cbciCascWorkshopControllerProvisionSecret"
      - resourceName: "projects/core-workshop/secrets/cbci-casc-workshop-user-api-token/versions/latest"
        fileName: "userApiToken" 
      - resourceName: "projects/core-workshop/secrets/cbci-workshop-example-credential-password/versions/latest"
        fileName: "cbciWorkshopExampleCredentialServicePassword"
