kind: Pod
apiVersion: v1
metadata:
  name: jcasc-controllers-secrets-store-inline
  namespace: controllers
spec:
  serviceAccount: jenkins
  containers:
    - name: busybox
      image: k8s.gcr.io/e2e-test-images/busybox:1.29
      command:
      - "/bin/sleep"
      - "999999999d"
      volumeMounts:
      - name: "jcasc-secrets"
        mountPath: "/var/jenkins_home/jcasc_secrets"
  volumes:
  - name: "jcasc-secrets"
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "cbci-mc-secret-provider"